name: 'npm'
description: 'Setup node, install and cache dependencies'

runs:
  using: composite

  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      shell: bash
      run: npm clean-install
